begin;

create table if not exists public.menu_categories (
  id bigint generated by default as identity primary key,
  hotel_slug text not null references public.hotel_profiles(hotel_slug) on update cascade on delete restrict,
  category_key text not null,
  name text not null,
  slug text not null,
  description text not null default '',
  display_order integer not null default 0 check (display_order >= 0),
  is_active boolean not null default true,
  is_published boolean not null default true,
  staff_enabled boolean not null default true,
  website_enabled boolean not null default true,
  qr_enabled boolean not null default true,
  default_image_url text,
  default_thumbnail_url text,
  image_storage_path text,
  image_alt_text text not null default '',
  image_version integer not null default 1 check (image_version > 0),
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint menu_categories_hotel_key_unique unique (hotel_slug, category_key),
  constraint menu_categories_hotel_slug_unique unique (hotel_slug, slug),
  constraint menu_categories_key_not_blank check (btrim(category_key) <> ''),
  constraint menu_categories_name_not_blank check (btrim(name) <> ''),
  constraint menu_categories_slug_not_blank check (btrim(slug) <> '')
);

create index if not exists idx_menu_categories_public
  on public.menu_categories (hotel_slug, is_active, is_published, website_enabled, display_order, name, id);

create index if not exists idx_menu_categories_staff
  on public.menu_categories (hotel_slug, is_active, staff_enabled, display_order, name, id);

create index if not exists idx_menu_categories_qr
  on public.menu_categories (hotel_slug, is_active, is_published, qr_enabled, display_order, name, id);

create unique index if not exists uq_menu_categories_active_name_per_hotel
  on public.menu_categories (hotel_slug, lower(name)) where is_active = true;

create index if not exists idx_menu_items_hotel_category_available_order
  on public.menu_items (hotel_slug, category, is_available, is_archived, sort_order, item_id);

insert into public.menu_categories (
  hotel_slug,
  category_key,
  name,
  slug,
  display_order,
  is_active,
  is_published,
  staff_enabled,
  website_enabled,
  qr_enabled
)
select
  source.hotel_slug,
  source.category_key,
  source.base_name || case
    when source.name_rank = 1 then ''
    else ' (' || source.name_rank::text || ')'
  end,
  source.base_slug || case when source.slug_rank = 1 then '' else '-' || source.slug_rank::text end,
  source.display_order,
  true,
  true,
  true,
  true,
  true
from (
  select
    grouped.*,
    row_number() over (
      partition by grouped.hotel_slug, grouped.base_slug
      order by grouped.display_order, grouped.category_key
    ) as slug_rank,
    row_number() over (
      partition by grouped.hotel_slug, lower(grouped.base_name)
      order by grouped.display_order, grouped.category_key
    ) as name_rank
  from (
    select
      hotel_slug,
      btrim(category) as category_key,
      initcap(replace(replace(btrim(category), '-', ' '), '_', ' ')) as base_name,
      coalesce(nullif(regexp_replace(lower(btrim(category)), '[^a-z0-9]+', '-', 'g'), ''), 'category') as base_slug,
      dense_rank() over (
        partition by hotel_slug
        order by min(sort_order), lower(btrim(category)), btrim(category)
      ) - 1 as display_order
    from public.menu_items
    where btrim(coalesce(category, '')) <> ''
    group by hotel_slug, btrim(category)
  ) grouped
) source
on conflict (hotel_slug, category_key) do nothing;

create table if not exists public.menu_category_audit (
  id bigint generated by default as identity primary key,
  hotel_slug text not null,
  category_id bigint,
  action text not null,
  actor text,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_menu_category_audit_hotel_category_created
  on public.menu_category_audit (hotel_slug, category_id, created_at desc);

comment on table public.menu_categories is
  'Authoritative hotel-scoped category registry. menu_items.category remains the compatible category_key relationship.';

comment on column public.menu_categories.category_key is
  'Stable key matched by menu_items.category. Change display name instead of changing this key.';

comment on table public.menu_category_audit is
  'Append-only category management history written by authenticated admin routes.';

commit;
