begin;

create table if not exists public.login_page_branding (
  id bigint generated by default as identity primary key,
  scope_type text not null check (scope_type in ('platform', 'hotel')),
  hotel_slug text null,
  draft_config jsonb not null default '{}'::jsonb,
  published_config jsonb null,
  is_published boolean not null default false,
  version integer not null default 0 check (version >= 0),
  created_by text null,
  updated_by text null,
  published_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz null,
  constraint login_page_branding_scope_check check (
    (scope_type = 'platform' and hotel_slug is null) or
    (scope_type = 'hotel' and hotel_slug is not null and length(btrim(hotel_slug)) >= 2)
  )
);

create unique index if not exists login_page_branding_platform_singleton_idx
  on public.login_page_branding (scope_type)
  where scope_type = 'platform';

create unique index if not exists login_page_branding_hotel_scope_idx
  on public.login_page_branding (lower(hotel_slug))
  where scope_type = 'hotel';

create index if not exists login_page_branding_public_lookup_idx
  on public.login_page_branding (scope_type, is_published, lower(hotel_slug));

create table if not exists public.login_page_branding_audit (
  id bigint generated by default as identity primary key,
  branding_id bigint null references public.login_page_branding(id) on delete set null,
  scope_type text not null check (scope_type in ('platform', 'hotel')),
  hotel_slug text null,
  action text not null check (action in (
    'draft_saved',
    'published',
    'reset',
    'image_uploaded',
    'image_removed'
  )),
  actor_id text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists login_page_branding_audit_scope_idx
  on public.login_page_branding_audit (scope_type, lower(hotel_slug), created_at desc);

insert into public.login_page_branding (
  scope_type,
  hotel_slug,
  draft_config,
  published_config,
  is_published,
  version
)
select
  'platform',
  null,
  jsonb_build_object(
    'companyName', 'AtithiSarthi',
    'shortCompanyName', 'AtithiSarthi',
    'shortProductLabel', 'Hospitality Operating System',
    'welcomeBadge', 'Hotel • Restaurant • Local Travel',
    'welcomeHeading', 'Welcome',
    'welcomeSubheading', 'Your Restaurant Operating System',
    'description', 'Manage stays, dining and guest service from one connected workspace.',
    'tagline', 'Serving Success Beyond the Kitchen.',
    'loginBadgeText', 'Secure Login',
    'loginHeading', 'Open your hotel billing view',
    'loginDescription', 'Use the hotel slug and staff PIN created for that hotel.',
    'hotelSlugLabel', 'Hotel Slug',
    'hotelSlugPlaceholder', 'Hotel Slug',
    'staffPinLabel', 'Staff PIN',
    'staffPinPlaceholder', 'Staff PIN',
    'loginButtonText', 'Login',
    'serviceSectionHeading', 'One connected journey',
    'enableHotelService', true,
    'hotelServiceLabel', 'Hotel / Stay',
    'enableRestaurantService', true,
    'restaurantServiceLabel', 'Restaurant / Dine',
    'enableTransportService', true,
    'transportServiceLabel', 'Local Travel',
    'footerCompanyName', 'AtithiSarthi',
    'copyrightText', 'Copyright © 2026 AtithiSarthi. All Rights Reserved.',
    'primaryColor', '#b86647',
    'secondaryColor', '#8c3f58',
    'accentColor', '#c49b3c',
    'backgroundColor', '#f7efe5',
    'cardColor', '#fffaf4',
    'textColor', '#281813'
  ),
  jsonb_build_object(
    'companyName', 'AtithiSarthi',
    'shortCompanyName', 'AtithiSarthi',
    'shortProductLabel', 'Hospitality Operating System',
    'welcomeBadge', 'Hotel • Restaurant • Local Travel',
    'welcomeHeading', 'Welcome',
    'welcomeSubheading', 'Your Restaurant Operating System',
    'description', 'Manage stays, dining and guest service from one connected workspace.',
    'tagline', 'Serving Success Beyond the Kitchen.',
    'loginBadgeText', 'Secure Login',
    'loginHeading', 'Open your hotel billing view',
    'loginDescription', 'Use the hotel slug and staff PIN created for that hotel.',
    'hotelSlugLabel', 'Hotel Slug',
    'hotelSlugPlaceholder', 'Hotel Slug',
    'staffPinLabel', 'Staff PIN',
    'staffPinPlaceholder', 'Staff PIN',
    'loginButtonText', 'Login',
    'serviceSectionHeading', 'One connected journey',
    'enableHotelService', true,
    'hotelServiceLabel', 'Hotel / Stay',
    'enableRestaurantService', true,
    'restaurantServiceLabel', 'Restaurant / Dine',
    'enableTransportService', true,
    'transportServiceLabel', 'Local Travel',
    'footerCompanyName', 'AtithiSarthi',
    'copyrightText', 'Copyright © 2026 AtithiSarthi. All Rights Reserved.',
    'primaryColor', '#b86647',
    'secondaryColor', '#8c3f58',
    'accentColor', '#c49b3c',
    'backgroundColor', '#f7efe5',
    'cardColor', '#fffaf4',
    'textColor', '#281813'
  ),
  true,
  1
where not exists (
  select 1 from public.login_page_branding where scope_type = 'platform'
);

revoke all on public.login_page_branding from anon, authenticated;
revoke all on public.login_page_branding_audit from anon, authenticated;
grant all on public.login_page_branding to service_role;
grant all on public.login_page_branding_audit to service_role;
grant usage, select on sequence public.login_page_branding_id_seq to service_role;
grant usage, select on sequence public.login_page_branding_audit_id_seq to service_role;

commit;
