-- Hotel-scoped restaurant table inventory. Existing behavior remains enabled
-- until a manager explicitly enables enforcement for a configured hotel.
create table if not exists public.restaurant_tables (
  id bigint generated by default as identity primary key,
  hotel_slug text not null,
  table_code text not null,
  table_name text not null default '',
  display_order integer not null default 0,
  capacity integer,
  area_name text not null default '',
  operational_status text not null default 'active',
  is_active boolean not null default true,
  created_by_staff_id bigint,
  updated_by_staff_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  row_version bigint not null default 1,
  constraint restaurant_tables_hotel_required check (btrim(hotel_slug) <> ''),
  constraint restaurant_tables_code_required check (btrim(table_code) <> ''),
  constraint restaurant_tables_code_length check (char_length(btrim(table_code)) <= 40),
  constraint restaurant_tables_name_length check (char_length(table_name) <= 120),
  constraint restaurant_tables_area_length check (char_length(area_name) <= 80),
  constraint restaurant_tables_order_range check (display_order between 0 and 1000000),
  constraint restaurant_tables_capacity_range check (capacity is null or capacity between 1 and 100),
  constraint restaurant_tables_status check (operational_status in ('active', 'maintenance', 'cleaning'))
);

create unique index if not exists uq_restaurant_tables_hotel_code
  on public.restaurant_tables (lower(btrim(hotel_slug)), lower(btrim(table_code)));
create index if not exists idx_restaurant_tables_hotel_floor
  on public.restaurant_tables (hotel_slug, is_active, operational_status, display_order, id);

alter table public.orders add column if not exists restaurant_table_id bigint;
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'orders_restaurant_table_id_fkey') then
    alter table public.orders add constraint orders_restaurant_table_id_fkey
      foreign key (restaurant_table_id) references public.restaurant_tables(id) on delete set null;
  end if;
end;
$$;
create index if not exists idx_orders_hotel_restaurant_table
  on public.orders (hotel_slug, restaurant_table_id, created_at desc);

alter table public.hotel_ordering_settings
  add column if not exists enforce_table_master boolean not null default false;

comment on table public.restaurant_tables is
  'Authoritative hotel-scoped restaurant table inventory shared by staff, QR, payments, KDS, and floor views.';
comment on column public.restaurant_tables.operational_status is
  'Configuration state only. Live service state is derived from the linked order.';
comment on column public.orders.restaurant_table_id is
  'Authoritative link for new table orders; table_number remains the compatible display snapshot.';

-- Link only exact normalized matches. Never rewrite historical table_number values.
update public.orders as orders
   set restaurant_table_id = matched_table.id
  from public.restaurant_tables as matched_table
 where orders.restaurant_table_id is null
   and lower(btrim(orders.hotel_slug)) = lower(btrim(matched_table.hotel_slug))
   and lower(btrim(coalesce(orders.table_number, ''))) = lower(btrim(matched_table.table_code))
   and btrim(coalesce(orders.table_number, '')) <> '';
